title: Zhuo Zhang
description: > # this means to ignore newlines until "baseurl:"




baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zhuozhang.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url:            https://zhuozhang.github.io
baseurl:        /

author:
  name:         'Zhuo Zhang'
  url:          https://zhuozhang.github.io
  email:        zhangzhuo dot nju at gmail dot com
  
github:
  repo:         https://github.com/zhuozhang

linkedin:
  url:          https://www.linkedin.com/in/zhuo-zhang-usc

exclude:        [_*~]

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
